#端口
server:
  port: 8607

spring:
  jmx:
    default-domain: mogu-gateway
  application:
    name: mogu-gateway
  security:
    user:
      name: user
      password: password123
  main:
    allow-bean-definition-overriding: true

  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8606
        username: user
        password: password123
    instance:
      service-base-url: http://localhost:8607

  cloud:
    gateway:
      discovery:  #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lowerCaseServiceId: true #使用小写服务名，默认是大写
      routes: # 配置路由规则, 
        - id: api-eureka
          uri: lb://mogu-eureka #loadbanlance
          predicates:
            - Path=/api-eureka/**

        - id: api-monitor
          uri: lb://mogu-monitor
          predicates:
            - Path=/api-monitor/**

        - id: api-picture
          uri: lb://mogu-picture
          predicates:
            - Path=/api-picture/**

        - id: api-web
          uri: lb://mogu-web
          predicates:
            - Path=/api-web/**

        - id: api-admin
          uri: lb://mogu-admin
          predicates:
            - Path=/api-admin/**
          filters:
            - StripPrefix=1 #前缀，在当前路径匹配中表示去掉第一个前缀
            - name: Hystrix #降级配置
              args:
                name: defaultfallback
                fallbackUri: forward:/defaultfallback

        - id: api-sms
          uri: lb://mogu-sms
          predicates:
            - Path=/api-sms/**

#设置最大超时时间
#ribbon:
#  eager-load:
#    enabled: true
#  ServerListRefreshInterval: 10  #刷新服务列表源的间隔时间
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true  
#  ReadTimeout: 90000  
#  ConnectTimeout: 90000 
#  OkToRetryOnAllOperations: true
#  MaxAutoRetries: 1
#  MaxAutoRetriesNextServer: 1
#  
##设置最大容错超时时间
# 针对全局配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    # 对单独的 Hystrix 的 commandKey 设置超时时间
    defaultfallback:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

#eureka相关配置
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always